import type { HrWorkbenchViewModel } from './types';

export const hrWorkbenchFixture: HrWorkbenchViewModel = {
  greeting: '上午好，沐白',
  dateText: '今天是 9 月 1 日 星期二',
  quickActions: [
    {
      key: 'upload',
      title: '上传简历',
      description: '单份或批量上传，自动解析并匹配',
      route: '/ai-assistants/hr/resumes/upload',
    },
    {
      key: 'matching',
      title: '查看匹配结果',
      description: '47 份待查看',
      route: '/ai-assistants/hr/matching',
    },
    {
      key: 'interview',
      title: '生成面试题',
      description: '基于匹配结果生成',
      route: '/ai-assistants/hr/interviews/generate',
    },
    {
      key: 'position',
      title: '岗位配置',
      description: '12 个启用中岗位',
      route: '/ai-assistants/hr/positions',
    },
  ],
  metrics: [
    { label: '新增简历', value: '47', comparisonText: '环比 +12%', tone: 'positive' },
    { label: '完成匹配', value: '39', comparisonText: '环比 +8%', tone: 'positive' },
    { label: '生成面试题', value: '12', comparisonText: '环比 +20%', tone: 'positive' },
    { label: '待处理事项', value: '5', comparisonText: '需要优先处理', tone: 'warning' },
  ],
  todos: [
    {
      id: 'low-confidence',
      content: '2 份简历解析置信度较低，需人工确认',
      detail: '后端开发工程师 · 20 分钟前',
      actionLabel: '去处理',
      route: '/ai-assistants/hr/resumes/corrections',
      tone: 'warning',
    },
    {
      id: 'filtered',
      content: '8 份简历被硬性条件过滤，建议检查是否误伤',
      detail: '后端开发工程师 · 1 小时前',
      actionLabel: '去查看',
      route: '/ai-assistants/hr/matching/filtered',
      tone: 'warning',
    },
    {
      id: 'configuration',
      content: '“销售经理”岗位权重合计 95%，配置未完成',
      detail: '3 天前',
      actionLabel: '去配置',
      route: '/ai-assistants/hr/positions/sales-manager/configuration',
      tone: 'warning',
    },
    {
      id: 'synonyms',
      content: '14 个技能未匹配到同义词库标准名',
      detail: '本周累计',
      actionLabel: '去处理',
      route: '/ai-assistants/hr/settings/skill-synonyms',
      tone: 'info',
    },
    {
      id: 'retention',
      content: '3 位候选人档案保留期剩余不足 30 天',
      detail: '人才库',
      actionLabel: '去查看',
      route: '/ai-assistants/hr/talent-pool',
      tone: 'info',
    },
  ],
  positions: [
    {
      id: 'backend',
      name: '后端开发工程师',
      matched: 39,
      stronglyRecommended: 5,
      recommended: 18,
      reviewSuggested: 12,
      notRecommended: 4,
      filtered: 8,
    },
    {
      id: 'frontend',
      name: '前端开发工程师',
      matched: 32,
      stronglyRecommended: 3,
      recommended: 12,
      reviewSuggested: 10,
      notRecommended: 7,
      filtered: 5,
    },
    {
      id: 'product',
      name: '产品经理',
      matched: 28,
      stronglyRecommended: 2,
      recommended: 9,
      reviewSuggested: 11,
      notRecommended: 6,
      filtered: 3,
    },
    {
      id: 'designer',
      name: '视觉设计师',
      matched: 19,
      stronglyRecommended: 1,
      recommended: 6,
      reviewSuggested: 8,
      notRecommended: 4,
      filtered: 2,
    },
    {
      id: 'analyst',
      name: '数据分析师',
      matched: 8,
      stronglyRecommended: 0,
      recommended: 2,
      reviewSuggested: 3,
      notRecommended: 3,
      filtered: 6,
    },
  ],
  activities: [
    { id: 'interview-edited', time: '10:24', actor: '你', content: '编辑了张伟的面试题集' },
    {
      id: 'manual-release',
      time: '10:15',
      actor: '你',
      content: '人工放行了吴磊的硬性条件“必须掌握 Python”',
    },
    {
      id: 'matching-completed',
      time: '09:45',
      actor: '系统',
      content: '完成 47 份简历与“后端开发工程师”的匹配',
    },
    {
      id: 'batch-completed',
      time: '09:42',
      actor: '系统',
      content: '批次 20260901-001 解析完成（成功 16 / 待确认 2 / 失败 1）',
    },
    {
      id: 'weight-adjusted',
      time: '09:30',
      actor: '你',
      content: '调整了“后端开发工程师”的权重配置（v1.1 → v1.2）',
    },
    { id: 'resumes-uploaded', time: '09:12', actor: '你', content: '上传了 19 份简历' },
  ],
};
